; PlatformIO Project Configuration File
; BMSCoreESP32 - ESP32-S3 BMS Integrated Firmware

[env:esp32-s3-wroom-n16r8]
platform = https://github.com/pioarduino/platform-espressif32.git
board = freenove_esp32_s3_wroom_n16r8
framework = arduino

board_build.filesystem = littlefs

upload_speed = 921600
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson@^7
    mathertel/OneButton@^2.6.2
    knolleary/PubSubClient@^2

lib_extra_dirs =
    middleware

lib_ignore =
    FreeRTOS

build_flags =
    -DBOARD_HAS_PSRAM
    -DLV_CONF_INCLUDE_SIMPLE
    -DBMS_ESP32
    -std=gnu++17
    -Isrc/bsp
    -Isrc/ui/src/hw
    -Isrc/ui/src
    -Isrc/ui/src/view
    -Isrc/ui/src/controller
    -Isrc/mqtt
    -Isrc/soc
    -Isrc/tasks
    -Imiddleware
    -I.

build_src_filter =
    +<*>
    +<tasks/>
    +<bsp/>
    +<app/>
    +<ui/src/>
    +<ui/fonts/>
    +<mqtt/>
    +<soc/>
