; PlatformIO Project Configuration File
; BMSCoreESP32 - ESP32-S3 BMS Integrated Firmware

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.arduino.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_build.filesystem = littlefs

board_upload.flash_size = 16MB

lib_deps =
    bblanchon/ArduinoJson@^7
    mathertel/OneButton@^2
    knolleary/PubSubClient@^2
    https://github.com/tzapu/WiFiManager.git#v2.0.17

lib_extra_dirs =
    middleware

lib_ignore =
    FreeRTOS

build_flags =
    -DBOARD_HAS_PSRAM
    -DLV_CONF_INCLUDE_SIMPLE
    -DBMS_ESP32
    -std=gnu++17
    -Isrc/bsp
    -Isrc/ui/src/hw
    -Isrc/ui/src
    -Isrc/ui/src/view
    -Isrc/ui/src/controller
    -Isrc/mqtt
    -Isrc/soc
    -Isrc/tasks
    -Imiddleware
    -I.

build_src_filter =
    +<*>
    +<tasks/>
    +<bsp/>
    +<app/>
    +<ui/src/>
    +<ui/fonts/>
    +<mqtt/>
    +<soc/>
